name: Gen Followers List - InsightAGI

run-name: Gen Followers List - InsightAGI

on:
  schedule:
    - cron: "0 1 * * 1,3,5" # Run every monday, wednesday and friday at 1:00 AM
  workflow_dispatch: # Manual dispatch

permissions:
  contents: write

env:
  GH_TOKEN: ${{ secrets.GH_PAT }}

defaults:
  run:
    shell: bash
    working-directory: ./scripts

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  gen-followers-list:
    name: Gen Forks List
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      
      - name: Configure git
        run: |
          git config --global user.name "github-actions[InsightAGI-bot]"
          git config --global user.email "github-actions[InsightAGI-bot]@users.noreply.github.com"
      
      - name: Run script gen-followers-list
        run: echo "InsightAGI" | ./gen-followers-list.sh
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
      
      - name: Commit changes
        run: |
          cd ..
          git add .
          git commit -m "Update Followers List for InsightAGI" || exit 0
        
      - name: Push changes
        run: git push
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
